=== raml-apis/Eloqua/schemas/bouncebackActivity-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "smtpErrorCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "smtpStatusCode" : {
      "type" : "string" ,
      "required" : false
    } ,
    "smtpMessage" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailFromAddress" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailToAddress" : {
      "type" : "string" ,
      "required" : false
    } ,
    "category" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "performedAt" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/bouncebackActivity-example.json
{
  "smtpErrorCode" : "undefined" ,
  "smtpStatusCode" : "undefined" ,
  "smtpMessage" : "undefined" ,
  "emailId" : "4821" ,
  "emailName" : "undefined" ,
  "emailFromAddress" : "undefined" ,
  "emailToAddress" : "undefined" ,
  "category" : "undefined" ,
  "id" : "undefined" ,
  "performedAt" : "undefined"
}
