=== raml-apis/Eloqua/schemas/campaign-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "startAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "endAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "budgetedCost" : {
      "type" : "string" ,
      "required" : false
    } ,
    "actualCost" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isMemberAllowedReEntry" : {
      "type" : "string" ,
      "required" : false
    } ,
    "fieldValues" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "value" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "elements" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "position" : {
              "type" : "object" ,
              "required" : false
            } ,
            "outputTerminals" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object" ,
                  "properties" : {
                    "terminalType" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "connectedType" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "connectedId" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "name" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "description" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "permissions" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "folderId" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "sourceTemplateId" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "createdBy" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "createdAt" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "updatedBy" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "updatedAt" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "accessedAt" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "scheduledFor" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "depth" : {
                      "type" : "string" ,
                      "required" : false
                    }
                  }
                }
              ]
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "description" : {
              "type" : "string" ,
              "required" : false
            } ,
            "permissions" : {
              "type" : "string" ,
              "required" : false
            } ,
            "folderId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "sourceTemplateId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "createdBy" : {
              "type" : "string" ,
              "required" : false
            } ,
            "createdAt" : {
              "type" : "string" ,
              "required" : false
            } ,
            "updatedBy" : {
              "type" : "string" ,
              "required" : false
            } ,
            "updatedAt" : {
              "type" : "string" ,
              "required" : false
            } ,
            "accessedAt" : {
              "type" : "string" ,
              "required" : false
            } ,
            "scheduledFor" : {
              "type" : "string" ,
              "required" : false
            } ,
            "depth" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "isReadOnly" : {
      "type" : "string" ,
      "required" : false
    } ,
    "campaignType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "product" : {
      "type" : "string" ,
      "required" : false
    } ,
    "region" : {
      "type" : "string" ,
      "required" : false
    } ,
    "crmId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/campaign-example.json
{
  "startAt" : "1358345068" ,
  "endAt" : "undefined" ,
  "budgetedCost" : "undefined" ,
  "actualCost" : "" ,
  "isMemberAllowedReEntry" : "undefined" ,
  "fieldValues" : [
    {
      "value" : "undefined" ,
      "id" : "undefined"
    }
  ] ,
  "elements" : [
    {
      "position" : {
      } ,
      "outputTerminals" : [
        {
          "terminalType" : "undefined" ,
          "connectedType" : "undefined" ,
          "connectedId" : "465" ,
          "name" : "undefined" ,
          "description" : "Eloqua" ,
          "permissions" : "undefined" ,
          "folderId" : "undefined" ,
          "sourceTemplateId" : "undefined" ,
          "createdBy" : "undefined" ,
          "createdAt" : "undefined" ,
          "updatedBy" : "undefined" ,
          "updatedAt" : "undefined" ,
          "accessedAt" : "undefined" ,
          "scheduledFor" : "undefined" ,
          "depth" : "minimal"
        }
      ] ,
      "name" : "undefined" ,
      "description" : "Eloqua" ,
      "permissions" : "undefined" ,
      "folderId" : "undefined" ,
      "sourceTemplateId" : "undefined" ,
      "createdBy" : "undefined" ,
      "createdAt" : "undefined" ,
      "updatedBy" : "undefined" ,
      "updatedAt" : "undefined" ,
      "accessedAt" : "undefined" ,
      "scheduledFor" : "undefined" ,
      "depth" : "minimal"
    }
  ] ,
  "isReadOnly" : "true" ,
  "campaignType" : "" ,
  "product" : "" ,
  "region" : "undefined" ,
  "crmId" : "undefined" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}

=== raml-apis/Eloqua/examples/optionList-example.json
{
  "elements" : [
    {
      "displayName" : "Sample Campaign" ,
      "value" : "undefined"
    }
  ] ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
