=== raml-apis/Eloqua/schemas/cloudComponent-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "iconUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "providerName" : {
      "type" : "string" ,
      "required" : false
    } ,
    "uptimeMetric" : {
      "type" : "string" ,
      "required" : false
    } ,
    "componentImage" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "url" : {
          "type" : "string" ,
          "required" : false
        } ,
        "height" : {
          "type" : "string" ,
          "required" : false
        } ,
        "width" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "isAvailable" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/cloudComponent-example.json
{
  "id" : "undefined" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "iconUrl" : "undefined" ,
  "providerName" : "undefined" ,
  "uptimeMetric" : "good" ,
  "componentImage" : {
    "url" : "undefined" ,
    "height" : "undefined" ,
    "width" : "undefined"
  } ,
  "isAvailable" : "undefined"
}
