=== raml-apis/Eloqua/schemas/contactEmailDeliverability-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "isGloballyExcludedByAddress" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isGloballyExcludedByDomain" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isEmailGroupUnsubscribed" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isMasterExcluded" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isSiteUnsubscribed" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isEmailResend" : {
      "type" : "string" ,
      "required" : false
    } ,
    "hasBouncedBack" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailAddress" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/contactEmailDeliverability-example.json
{
  "isGloballyExcludedByAddress" : "undefined" ,
  "isGloballyExcludedByDomain" : "undefined" ,
  "isEmailGroupUnsubscribed" : "false" ,
  "isMasterExcluded" : "undefined" ,
  "isSiteUnsubscribed" : "undefined" ,
  "isEmailResend" : "undefined" ,
  "hasBouncedBack" : "undefined" ,
  "emailAddress" : "fred.sakr@eloqua.com" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
