=== raml-apis/Eloqua/schemas/contactEmailSubscription-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "contactId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "emailGroup" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "emailHeaderId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "emailFooterId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "subscriptionLandingPageId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "unsubscriptionLandingPageId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "isVisibleInPublicSubscriptionList" : {
          "type" : "string" ,
          "required" : false
        } ,
        "isVisibleInOutlookPlugin" : {
          "type" : "string" ,
          "required" : false
        } ,
        "emailIds" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object"
            }
          ]
        } ,
        "displayName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "subscriptionListId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "unSubscriptionListId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "subscriptionListDataLookupId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "unSubscriptionListDataLookupId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "description" : {
          "type" : "string" ,
          "required" : false
        } ,
        "permissions" : {
          "type" : "string" ,
          "required" : false
        } ,
        "folderId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "sourceTemplateId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "accessedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "scheduledFor" : {
          "type" : "string" ,
          "required" : false
        } ,
        "depth" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "isSubscribed" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/contactEmailSubscription-example.json
{
  "contactId" : "undefined" ,
  "emailGroup" : {
    "emailHeaderId" : "undefined" ,
    "emailFooterId" : "undefined" ,
    "subscriptionLandingPageId" : "undefined" ,
    "unsubscriptionLandingPageId" : "2" ,
    "isVisibleInPublicSubscriptionList" : "undefined" ,
    "isVisibleInOutlookPlugin" : "false" ,
    "emailIds" : [
      null ,
      null
    ] ,
    "displayName" : "Sample Campaign" ,
    "subscriptionListId" : "undefined" ,
    "unSubscriptionListId" : "undefined" ,
    "subscriptionListDataLookupId" : "undefined" ,
    "unSubscriptionListDataLookupId" : "undefined" ,
    "name" : "string string" ,
    "description" : "string string" ,
    "permissions" : "InstancePermissions InstancePermissions" ,
    "folderId" : "string string" ,
    "sourceTemplateId" : "string string" ,
    "createdBy" : "string string" ,
    "createdAt" : "dateTime dateTime" ,
    "updatedBy" : "string string" ,
    "updatedAt" : "dateTime dateTime" ,
    "accessedAt" : "dateTime dateTime" ,
    "scheduledFor" : "dateTime dateTime" ,
    "depth" : "RequestDepth RequestDepth"
  } ,
  "isSubscribed" : "undefined" ,
  "updatedAt" : "undefined"
}
