=== raml-apis/Eloqua/schemas/dataImport-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "purpose" : {
      "type" : "string" ,
      "required" : false
    } ,
    "dataImportPriorityId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceFieldIds" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object"
        }
      ]
    } ,
    "fieldMappings" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "sourceFieldId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "targetFieldId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "isLookup" : {
              "type" : "string" ,
              "required" : false
            } ,
            "updateType" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "notification" : {
      "type" : "object" ,
      "required" : false
    } ,
    "listId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isAutomated" : {
      "type" : "string" ,
      "required" : false
    } ,
    "lastUpdatedSourceFieldsAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/dataImport-example.json
{
  "purpose" : "undefined" ,
  "dataImportPriorityId" : "undefined" ,
  "sourceFieldIds" : [
    null ,
    null
  ] ,
  "fieldMappings" : [
    {
      "sourceFieldId" : "undefined" ,
      "targetFieldId" : "undefined" ,
      "isLookup" : "true" ,
      "updateType" : "undefined"
    }
  ] ,
  "notification" : {
  } ,
  "listId" : "undefined" ,
  "isAutomated" : "undefined" ,
  "lastUpdatedSourceFieldsAt" : "undefined" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
