=== raml-apis/Eloqua/schemas/dataField-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "optionListId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "checkedValue" : {
      "type" : "string" ,
      "required" : false
    } ,
    "uncheckedValue" : {
      "type" : "string" ,
      "required" : false
    } ,
    "displayType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "dataType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "defaultValue" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isReadOnly" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isRequired" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isStandard" : {
      "type" : "string" ,
      "required" : false
    } ,
    "outputFormatId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/accountField-example.json
{
  "optionListId" : "1" ,
  "checkedValue" : "undefined" ,
  "uncheckedValue" : "undefined" ,
  "displayType" : "undefined" ,
  "dataType" : "undefined" ,
  "defaultValue" : "undefined" ,
  "isReadOnly" : "true" ,
  "isRequired" : "false" ,
  "isStandard" : "undefined" ,
  "outputFormatId" : "undefined"
}

=== raml-apis/Eloqua/examples/dataField-example.json
{
  "optionListId" : "1" ,
  "checkedValue" : "undefined" ,
  "uncheckedValue" : "undefined" ,
  "displayType" : "undefined" ,
  "dataType" : "undefined" ,
  "defaultValue" : "undefined" ,
  "isReadOnly" : "true" ,
  "isRequired" : "false" ,
  "isStandard" : "undefined" ,
  "outputFormatId" : "undefined" ,
  "name" : "string string" ,
  "description" : "string string" ,
  "permissions" : "InstancePermissions InstancePermissions" ,
  "folderId" : "string string" ,
  "sourceTemplateId" : "string string" ,
  "createdBy" : "string string" ,
  "createdAt" : "dateTime dateTime" ,
  "updatedBy" : "string string" ,
  "updatedAt" : "dateTime dateTime" ,
  "accessedAt" : "dateTime dateTime" ,
  "scheduledFor" : "dateTime dateTime" ,
  "depth" : "RequestDepth RequestDepth"
}

=== raml-apis/Eloqua/examples/customObjectField-example.json
{
  "displayType" : "undefined" ,
  "dataType" : "undefined" ,
  "defaultValue" : "undefined" ,
  "name" : "string string" ,
  "description" : "string string" ,
  "permissions" : "InstancePermissions InstancePermissions" ,
  "folderId" : "string string" ,
  "sourceTemplateId" : "string string" ,
  "createdBy" : "string string" ,
  "createdAt" : "dateTime dateTime" ,
  "updatedBy" : "string string" ,
  "updatedAt" : "dateTime dateTime" ,
  "accessedAt" : "dateTime dateTime" ,
  "scheduledFor" : "dateTime dateTime" ,
  "depth" : "RequestDepth RequestDepth"
}
