=== raml-apis/Eloqua/schemas/documentStyle-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "page" : {
      "type" : "string" ,
      "required" : false
    } ,
    "header" : {
      "type" : "string" ,
      "required" : false
    } ,
    "footer" : {
      "type" : "string" ,
      "required" : false
    } ,
    "body" : {
      "type" : "string" ,
      "required" : false
    } ,
    "column1" : {
      "type" : "string" ,
      "required" : false
    } ,
    "column2" : {
      "type" : "string" ,
      "required" : false
    } ,
    "column3" : {
      "type" : "string" ,
      "required" : false
    } ,
    "headline" : {
      "type" : "string" ,
      "required" : false
    } ,
    "icon" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/documentStyle-example.json
{
  "page" : "undefined" ,
  "header" : "undefined" ,
  "footer" : "undefined" ,
  "body" : "undefined" ,
  "column1" : "undefined" ,
  "column2" : "undefined" ,
  "column3" : "undefined" ,
  "headline" : "undefined" ,
  "icon" : "undefined" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
