=== raml-apis/Eloqua/schemas/export-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "notification" : {
      "type" : "object" ,
      "required" : false
    } ,
    "fileFormat" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "columnDelimiter" : {
          "type" : "string" ,
          "required" : false
        } ,
        "encoding" : {
          "type" : "string" ,
          "required" : false
        } ,
        "extension" : {
          "type" : "string" ,
          "required" : false
        } ,
        "rowDelimiter" : {
          "type" : "string" ,
          "required" : false
        } ,
        "textQualifier" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "fileLifetime" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isFileCompressed" : {
      "type" : "string" ,
      "required" : false
    } ,
    "isDelta" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/export-example.json
{
  "notification" : {
  } ,
  "fileFormat" : {
    "columnDelimiter" : "undefined" ,
    "encoding" : "undefined" ,
    "extension" : "undefined" ,
    "rowDelimiter" : "undefined" ,
    "textQualifier" : "undefined"
  } ,
  "fileLifetime" : "undefined" ,
  "isFileCompressed" : "undefined" ,
  "isDelta" : "undefined"
}
