=== raml-apis/Eloqua/schemas/imageFile-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "fullImageUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "size" : {
      "type" : "object" ,
      "required" : false
    } ,
    "thumbnailUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/imageFile-example.json
{
  "fullImageUrl" : "/EloquaImages/clients/ORSE/{ffaa51ba-220e-43da-994f-197338be7d35}_sample.jpg" ,
  "size" : {
  } ,
  "thumbnailUrl" : "/EloquaImages/clients/ORSE/imagethumbnails/{ffaa51ba-220e-43da-994f-197338be7d35}_sample.jpg" ,
  "name" : "string string" ,
  "description" : "string string" ,
  "permissions" : "InstancePermissions InstancePermissions" ,
  "folderId" : "string string" ,
  "sourceTemplateId" : "string string" ,
  "createdBy" : "string string" ,
  "createdAt" : "dateTime dateTime" ,
  "updatedBy" : "string string" ,
  "updatedAt" : "dateTime dateTime" ,
  "accessedAt" : "dateTime dateTime" ,
  "scheduledFor" : "dateTime dateTime" ,
  "depth" : "RequestDepth RequestDepth"
}
