=== raml-apis/Eloqua/schemas/scheduledImport-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "importInfo" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "purpose" : {
          "type" : "string" ,
          "required" : false
        } ,
        "dataImportPriorityId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "sourceFieldIds" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object"
            }
          ]
        } ,
        "fieldMappings" : {
          "type" : "array" ,
          "required" : false ,
          "items" : [
            {
              "type" : "object" ,
              "properties" : {
                "sourceFieldId" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "targetFieldId" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "isLookup" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "updateType" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            }
          ]
        } ,
        "notification" : {
          "type" : "object" ,
          "required" : false
        } ,
        "listId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "isAutomated" : {
          "type" : "string" ,
          "required" : false
        } ,
        "lastUpdatedSourceFieldsAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "description" : {
          "type" : "string" ,
          "required" : false
        } ,
        "permissions" : {
          "type" : "string" ,
          "required" : false
        } ,
        "folderId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "sourceTemplateId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "accessedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "scheduledFor" : {
          "type" : "string" ,
          "required" : false
        } ,
        "depth" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "sourceConnection" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "hostname" : {
          "type" : "string" ,
          "required" : false
        } ,
        "username" : {
          "type" : "string" ,
          "required" : false
        } ,
        "password" : {
          "type" : "string" ,
          "required" : false
        } ,
        "port" : {
          "type" : "string" ,
          "required" : false
        } ,
        "name" : {
          "type" : "string" ,
          "required" : false
        } ,
        "description" : {
          "type" : "string" ,
          "required" : false
        } ,
        "permissions" : {
          "type" : "string" ,
          "required" : false
        } ,
        "folderId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "sourceTemplateId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "createdAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedBy" : {
          "type" : "string" ,
          "required" : false
        } ,
        "updatedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "accessedAt" : {
          "type" : "string" ,
          "required" : false
        } ,
        "scheduledFor" : {
          "type" : "string" ,
          "required" : false
        } ,
        "depth" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "sourcePath" : {
      "type" : "string" ,
      "required" : false
    } ,
    "executedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "executionStatus" : {
      "type" : "string" ,
      "required" : false
    } ,
    "schedule" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "displayTimeZoneId" : {
          "type" : "string" ,
          "required" : false
        } ,
        "details" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "dailyStartTime" : {
              "type" : "string" ,
              "required" : false
            } ,
            "dailyEndTime" : {
              "type" : "string" ,
              "required" : false
            } ,
            "days" : {
              "type" : "array" ,
              "required" : false ,
              "items" : [
                {
                  "type" : "object"
                }
              ]
            }
          }
        } ,
        "executionInterval" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/scheduledTask-example.json
{
  "executedAt" : "undefined" ,
  "executionStatus" : "undefined" ,
  "schedule" : {
    "displayTimeZoneId" : "undefined" ,
    "details" : {
      "dailyStartTime" : "undefined" ,
      "dailyEndTime" : "undefined" ,
      "days" : [
        null ,
        null
      ]
    } ,
    "executionInterval" : "undefined"
  } ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}

=== raml-apis/Eloqua/examples/scheduledImport-example.json
{
  "importInfo" : {
    "purpose" : "undefined" ,
    "dataImportPriorityId" : "undefined" ,
    "sourceFieldIds" : [
      null ,
      null
    ] ,
    "fieldMappings" : [
      {
        "sourceFieldId" : "undefined" ,
        "targetFieldId" : "undefined" ,
        "isLookup" : "true" ,
        "updateType" : "undefined"
      }
    ] ,
    "notification" : {
    } ,
    "listId" : "undefined" ,
    "isAutomated" : "undefined" ,
    "lastUpdatedSourceFieldsAt" : "undefined" ,
    "name" : "string string" ,
    "description" : "string string" ,
    "permissions" : "InstancePermissions InstancePermissions" ,
    "folderId" : "string string" ,
    "sourceTemplateId" : "string string" ,
    "createdBy" : "string string" ,
    "createdAt" : "dateTime dateTime" ,
    "updatedBy" : "string string" ,
    "updatedAt" : "dateTime dateTime" ,
    "accessedAt" : "dateTime dateTime" ,
    "scheduledFor" : "dateTime dateTime" ,
    "depth" : "RequestDepth RequestDepth"
  } ,
  "sourceConnection" : {
    "hostname" : "undefined" ,
    "username" : "undefined" ,
    "password" : "undefined" ,
    "port" : "undefined" ,
    "name" : "string string" ,
    "description" : "string string" ,
    "permissions" : "InstancePermissions InstancePermissions" ,
    "folderId" : "string string" ,
    "sourceTemplateId" : "string string" ,
    "createdBy" : "string string" ,
    "createdAt" : "dateTime dateTime" ,
    "updatedBy" : "string string" ,
    "updatedAt" : "dateTime dateTime" ,
    "accessedAt" : "dateTime dateTime" ,
    "scheduledFor" : "dateTime dateTime" ,
    "depth" : "RequestDepth RequestDepth"
  } ,
  "sourcePath" : "undefined" ,
  "executedAt" : "undefined" ,
  "executionStatus" : "undefined" ,
  "schedule" : {
    "displayTimeZoneId" : "undefined" ,
    "details" : {
      "dailyStartTime" : "undefined" ,
      "dailyEndTime" : "undefined" ,
      "days" : [
        null ,
        null
      ]
    } ,
    "executionInterval" : "undefined"
  } ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
