=== raml-apis/Eloqua/schemas/site-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "domainRootSecure" : {
      "type" : "string" ,
      "required" : false
    } ,
    "domainRoot" : {
      "type" : "string" ,
      "required" : false
    } ,
    "pulseUrl" : {
      "type" : "string" ,
      "required" : false
    } ,
    "idleTime" : {
      "type" : "string" ,
      "required" : false
    } ,
    "productTrim" : {
      "type" : "string" ,
      "required" : false
    } ,
    "defaultContactImportSourceId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "components" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object"
        }
      ]
    } ,
    "enableClientLogging" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permissions" : {
      "type" : "string" ,
      "required" : false
    } ,
    "folderId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sourceTemplateId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "createdAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedBy" : {
      "type" : "string" ,
      "required" : false
    } ,
    "updatedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessedAt" : {
      "type" : "string" ,
      "required" : false
    } ,
    "scheduledFor" : {
      "type" : "string" ,
      "required" : false
    } ,
    "depth" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Eloqua/examples/site-example.json
{
  "domainRootSecure" : "undefined" ,
  "domainRoot" : "mktgchallenge.eloqua.com" ,
  "pulseUrl" : "undefined" ,
  "idleTime" : "undefined" ,
  "productTrim" : "undefined" ,
  "defaultContactImportSourceId" : "undefined" ,
  "components" : [
    null ,
    null
  ] ,
  "enableClientLogging" : "undefined" ,
  "name" : "undefined" ,
  "description" : "Eloqua" ,
  "permissions" : "undefined" ,
  "folderId" : "undefined" ,
  "sourceTemplateId" : "undefined" ,
  "createdBy" : "undefined" ,
  "createdAt" : "undefined" ,
  "updatedBy" : "undefined" ,
  "updatedAt" : "undefined" ,
  "accessedAt" : "undefined" ,
  "scheduledFor" : "undefined" ,
  "depth" : "minimal"
}
